//
// Created by Killian Zhou on 14/04/2024.
//

#ifndef ICESMARTDESK_CONSTANTS_H
#define ICESMARTDESK_CONSTANTS_H

#define TFT_ICE_DARK_BLUE 0x11A9
#define TFT_ICE_LIGHT_BLUE 0xCEFD
#define TFT_TEMP_BLUE 0x061F
#define TFT_TEMP_RED 0xF800
#define TFT_TEMP_ORANGE 0xFEA0

#endif //ICESMARTDESK_CONSTANTS_H
